### ISSUE TITLE
Update: Jetpack Plugin

### ISSUE THREAD

**Issue by QbpNogCYUGmaGPzD** [ONGEkUNSTELD/ONGEkUNSTELD#11]
Je kunt de Jetpack plugin lokaal activeren, zodat je infinite scroll krijgt, social sharing buttons, enz. De plugin herkent dat je de site lokaal draait en gaat automatisch in dev-mode. Heel netjes.
Dan weet je dat!

**Comment by ntenhoedt** [comment]
Tof! Kun je uitleggen hoe ik het font krijg? Moet ik een nieuwe sync doen?
