### ISSUE TITLE
Artikel delen op social media stijlen

### ISSUE THREAD

**Issue by ntenhoedt** [ONGEkUNSTELD/ONGEkUNSTELD#14]

**Comment by QbpNogCYUGmaGPzD** [comment]
Wat had je precies in gedachten?

**Comment by ntenhoedt** [comment]
De social media links onder een artikel kunnen nog een kleine styling gebruiken. Ik denk misschien de links op een aparte regel en centreren in het vlak. Kopje voor de links mag volgens mij in het zwart ipv grijs

**Comment by QbpNogCYUGmaGPzD** [comment]
Prima. Als we ergens aan beginnen moeten we bij die issue onszelf als Assignee zetten. Op die manier weten we ook wie aan welk ding werkt. Je eigen issues ben je standaard de assignee, maar als je eraan begint moet je het even extra bevestigen. Op die manier werken we niet aan hetzelfde. Er is niet echt een handige methode om issues aan branches te koppelen, behalve in een issue laten weten dat je eraan werkt en de naam van je branche erin te pasten of zo.

**Comment by ntenhoedt** [comment]
ok prima!
