### ISSUE TITLE
padding bovenkant single page (beeld mag niet bovenbalk aanraken)

### ISSUE THREAD

**Issue by ntenhoedt** [ONGEkUNSTELD/ONGEkUNSTELD#15]
gelijk trekken met auteurspagina

**Comment by QbpNogCYUGmaGPzD** [comment]
Is een lastige, omdat het enkel op single page zo moet zijn. Is het een idee om op een single.page een extra divje te bouwen van 50px height?

**Comment by ntenhoedt** [comment]
ik geloof dat de ruimte op de auteurspagina's bovenaan ook een div is. wat mij betreft copy pasten we die. We kunnen daar ook gelijk de tekst over de auteur in plaatsen denk ik. De titel van de category stond in die div

**Comment by QbpNogCYUGmaGPzD** [comment]
```
Dat zou een mooie oplossing zijn.
Ik ga nu eten, en dan heb ik een meeting. Morgen weer verder. Werkt
lekker zo!




On 2-4-2015 17:43, ntenhoedt wrote:


  ik geloof dat de ruimte op de auteurspagina's bovenaan ook een
    div is. wat mij betreft copy pasten we die. We kunnen daar ook
    gelijk de tekst over de auteur in plaatsen denk ik. De titel van
    de category stond in die div
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by ntenhoedt** [comment]
Ja top!

**Comment by QbpNogCYUGmaGPzD** [comment]
e6b752b8145fab0175de01f8eee1d468629450a2
#55
