### ISSUE TITLE
Verspringing op homepage van artikel 1

### ISSUE THREAD

**Issue by ntenhoedt** [ONGEkUNSTELD/ONGEkUNSTELD#6]

**Comment by QbpNogCYUGmaGPzD** [comment]
Ja dat is een serieuze. Ik vermoed dat het te maken heeft met de 'toevoeging' van de shadow na de scroll. Maar kijk ook rond in de JS folder, daar zitten wat resten in die eigenlijk opgeruimd moeten worden.

**Comment by QbpNogCYUGmaGPzD** [comment]
Check branch 47934174c28e90c0d9fe39abbe66fa59c6b9de8f
