### ISSUE TITLE
Let op eerst syncen!

### ISSUE THREAD

**Issue by QbpNogCYUGmaGPzD** [ONGEkUNSTELD/ONGEkUNSTELD#68]
@ntenhoedt 
Als je weer verder werkt aan de site, sync dan eerst je GitHub met de master. Ik heb wat dingen gemerged, dus de master is veranderd.
Close maar als je gelezen hebt.

**Comment by QbpNogCYUGmaGPzD** [comment]
@marco-van-zomeren

**Comment by QbpNogCYUGmaGPzD** [comment]
@ntenhoedt nu gelezen?! ;)

**Comment by ntenhoedt** [comment]
jahoor
