### ISSUE TITLE
Tabelweergave fixxen

### ISSUE THREAD

**Issue by QbpNogCYUGmaGPzD** [ONGEkUNSTELD/ONGEkUNSTELD#71]
https://www.ongekunsteld.net/overzicht-aanvragen/

**Comment by marco-van-zomeren** [comment]
Wat dient er exact gefixt te worden?

**Comment by QbpNogCYUGmaGPzD** [comment]
Nu ziet het er 'okee' uit, maar als er meerdere waardes in een tabel komen looppt de tabel buiten het witte vlak. Ik zat er aan te denken om een template pagina te maken die de hele breedte pakt.

**Comment by marco-van-zomeren** [comment]
Ja, dat lijkt me de simpelste oplossing, wellicht ook gewoon de beste.

**Comment by QbpNogCYUGmaGPzD** [comment]
Ik heb daar al eens mee zitten worstelen, https://github.com/ONGEkUNSTELD/ONGEkUNSTELD/tree/master/page-templates Maar daar moet ik nog wel veel aan uitvogelen.

**Comment by marco-van-zomeren** [comment]
.page-template-full-width .entry-header, .entry-content {
    max-width: 1000px!important;
}

should do the trick

**Comment by QbpNogCYUGmaGPzD** [comment]
marco!important;

**Comment by QbpNogCYUGmaGPzD** [comment]
Helaas, dit komt op alle pages uit op een 1280 breedte. Er moet meer gespecificeerd worden.

**Comment by marco-van-zomeren** [comment]
Zie: https://github.com/ONGEkUNSTELD/ONGEkUNSTELD/pull/73

**Comment by QbpNogCYUGmaGPzD** [comment]
Done en gemerged.
